
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.allocator-api2]]
version = "0.2.21"
criteria = "safe-to-run"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.apalis]]
version = "1.0.0-beta.2"
criteria = "safe-to-run"

[[exemptions.apalis-core]]
version = "1.0.0-beta.2"
criteria = "safe-to-deploy"

[[exemptions.apalis-sql]]
version = "1.0.0-beta.1"
criteria = "safe-to-run"

[[exemptions.apalis-sql]]
version = "1.0.0-beta.2"
criteria = "safe-to-run"

[[exemptions.apalis-workflow]]
version = "0.1.0-beta.1"
criteria = "safe-to-run"

[[exemptions.apalis-workflow]]
version = "0.1.0-beta.2"
criteria = "safe-to-run"

[[exemptions.atoi]]
version = "2.0.0"
criteria = "safe-to-run"

[[exemptions.atoi]]
version = "2.0.0"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-run"

[[exemptions.base64ct]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.10.0"
criteria = "safe-to-run"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.19.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.46"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.47"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.46"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.crc]]
version = "3.3.0"
criteria = "safe-to-run"

[[exemptions.crc]]
version = "3.4.0"
criteria = "safe-to-run"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.crc]]
version = "3.3.0"
criteria = "safe-to-run"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-run"

[[exemptions.cron]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-queue]]
version = "0.3.12"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.crypto-common]]
version = "0.1.7"
criteria = "safe-to-run"

[[exemptions.der]]
version = "0.7.10"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-run"

[[exemptions.english-to-cron]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.english-to-cron]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.dotenvy]]
version = "0.15.7"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.15.0"
criteria = "safe-to-run"

[[exemptions.english-to-cron]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.etcetera]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.event-listener]]
version = "5.4.1"
criteria = "safe-to-run"

[[exemptions.find-msvc-tools]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-run"

[[exemptions.flume]]
version = "0.11.1"
criteria = "safe-to-run"

[[exemptions.foldhash]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.form_urlencoded]]
version = "1.2.2"
criteria = "safe-to-run"

[[exemptions.futures]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.futures-intrusive]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.futures-io]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.16.1"
criteria = "safe-to-run"

[[exemptions.hashlink]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.home]]
version = "0.5.12"
criteria = "safe-to-run"

[[exemptions.home]]
version = "0.5.11"
criteria = "safe-to-run"

[[exemptions.iana-time-zone]]
version = "0.1.64"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-run"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-run"

[[exemptions.home]]
version = "0.5.12"
criteria = "safe-to-run"

[[exemptions.iana-time-zone]]
version = "0.1.64"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "2.1.1"
criteria = "safe-to-run"

[[exemptions.icu_locale_core]]
version = "2.1.1"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.12.0"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.12.1"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.83"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.5.0"
criteria = "safe-to-run"

[[exemptions.icu_properties_data]]
version = "2.1.1"
criteria = "safe-to-run"

[[exemptions.icu_provider]]
version = "2.1.1"
criteria = "safe-to-run"

[[exemptions.idna]]
version = "1.1.0"
criteria = "safe-to-run"

[[exemptions.idna_adapter]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.12.0"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.5.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.177"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.libsqlite3-sys]]
version = "0.30.1"
criteria = "safe-to-run"

[[exemptions.litemap]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.litrs]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.14"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.28"
criteria = "safe-to-deploy"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.7.6"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.1.0"
criteria = "safe-to-run"

[[exemptions.num-bigint-dig]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.num-integer]]
version = "0.1.46"
criteria = "safe-to-run"

[[exemptions.num-iter]]
version = "0.1.45"
criteria = "safe-to-run"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-run"

[[exemptions.parking_lot]]
version = "0.12.5"
criteria = "safe-to-run"

[[exemptions.parking_lot_core]]
version = "0.9.12"
criteria = "safe-to-run"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.percent-encoding]]
version = "2.3.2"
criteria = "safe-to-run"

[[exemptions.petgraph]]
version = "0.8.3"
criteria = "safe-to-run"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.pkcs1]]
version = "0.7.5"
criteria = "safe-to-run"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-run"

[[exemptions.pkg-config]]
version = "0.3.32"
criteria = "safe-to-run"

[[exemptions.potential_utf]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.103"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.42"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.rand]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-run"

[[exemptions.rand_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.12.2"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-run"

[[exemptions.rsa]]
version = "0.9.9"
criteria = "safe-to-run"

[[exemptions.rustls]]
version = "0.23.35"
criteria = "safe-to-run"

[[exemptions.rustls-pki-types]]
version = "1.13.0"
criteria = "safe-to-run"

[[exemptions.rustls-webpki]]
version = "0.103.8"
criteria = "safe-to-run"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.signal-hook-registry]]
version = "1.4.6"
criteria = "safe-to-run"

[[exemptions.signal-hook-registry]]
version = "1.4.7"
criteria = "safe-to-run"

[[exemptions.signature]]
version = "2.2.0"
criteria = "safe-to-run"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.145"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-run"

[[exemptions.sha1]]
version = "0.10.6"
criteria = "safe-to-run"

[[exemptions.sha2]]
version = "0.10.9"
criteria = "safe-to-run"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.6"
criteria = "safe-to-run"

[[exemptions.signature]]
version = "2.2.0"
criteria = "safe-to-run"

[[exemptions.slab]]
version = "0.4.11"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.15.1"
criteria = "safe-to-run"

[[exemptions.socket2]]
version = "0.6.1"
criteria = "safe-to-run"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-run"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.110"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.111"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.sqlx-macros]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.sqlx-macros-core]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.sqlx-mysql]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.sqlx-postgres]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.sqlx-sqlite]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.stringprep]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.110"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.synstructure]]
version = "0.13.2"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "2.0.17"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.17"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.tokio]]
version = "1.48.0"
criteria = "safe-to-run"

[[exemptions.tokio-macros]]
version = "2.6.0"
criteria = "safe-to-run"

[[exemptions.tokio-stream]]
version = "0.1.17"
criteria = "safe-to-run"

[[exemptions.tokio-util]]
version = "0.7.17"
criteria = "safe-to-run"

[[exemptions.tower]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.41"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-run"

[[exemptions.ulid]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.106"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.unicode-properties]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.url]]
version = "2.5.7"
criteria = "safe-to-run"

[[exemptions.utf8_iter]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.vcpkg]]
version = "0.2.15"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-run"

[[exemptions.wasip2]]
version = "1.0.1+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.wasite]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.11"
criteria = "safe-to-run"

[[exemptions.webpki-roots]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.whoami]]
version = "1.6.1"
criteria = "safe-to-run"

[[exemptions.windows-core]]
version = "0.62.2"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.3"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.53.5"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.53.1"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.53.1"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.53.1"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.30"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.53.1"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.53.1"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.6.26"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.writeable]]
version = "0.6.2"
criteria = "safe-to-run"

[[exemptions.yoke]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.yoke-derive]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerofrom]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.zerofrom-derive]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-run"

[[exemptions.zerotrie]]
version = "0.2.3"
criteria = "safe-to-run"

[[exemptions.zerovec]]
version = "0.11.5"
criteria = "safe-to-run"

[[exemptions.zerovec-derive]]
version = "0.11.2"
criteria = "safe-to-run"
